00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/models.py
from .exts import db

# 创建一个项目, 用来说明出版社, 书籍和作者的关系。
# 假定关系：作者：书籍 => 1:n  （一本书由一个作者完成， 一个作者可以创作多本书）
# 		 出版社：书籍 => n:n  （一个出版社可以出版多本书， 一本书可以由多个出版社出版）

# 作者
class Author(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(30))
    age = db.Column(db.Integer, default=1)
    sex = db.Column(db.Boolean, default=True)
    email = db.Column(db.String(200))
    # 关系
    books = db.relationship('Book', backref='auther', lazy='dynamic')

# 书籍
class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(100), unique=True)
    date = db.Column(db.DateTime)
    # 1对多，外键
    author_id = db.Column(db.Integer, db.ForeignKey(Author.id))


# 中间表（书籍-出版社）
book_publisher = db.Table(
    'book_publisher',
    db.Column('book_id', db.Integer,
              db.ForeignKey('book.id'), primary_key=True),
    db.Column('publisher_id', db.Integer,
              db.ForeignKey('publisher.id'), primary_key=True)
)

# 出版社
class Publisher(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(20), unique=True)
    address = db.Column(db.String(200))
    city = db.Column(db.String(100))
    province = db.Column(db.String(100))
    country = db.Column(db.String(100))
    website = db.Column(db.String(100))
    # 多对多, 关联book表
    books = db.relationship('Book', backref='publishers',
                            secondary=book_publisher, lazy='dynamic')

00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/__init__.py
# __init__.py ：初始化文件，创建Flask应用

from flask import Flask
from .views import blue
from .exts import init_exts


def create_app():
    app = Flask(__name__)
    # 注册蓝图
    app.register_blueprint(blueprint=blue)

    # 配置数据库
    # db_uri = 'sqlite:///sqlite3.db'  # sqlite配置
    db_uri = 'mysql+pymysql://root:123456@localhost:3306/bookdb'  # mysql的配置
    app.config['SQLALCHEMY_DATABASE_URI'] = db_uri
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False  # 禁止对象追踪修改

    # 初始化插件（写在配置数据库之后）
    init_exts(app=app)

    return app

00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/views.py
from flask import Blueprint, request, render_template
from .models import *

# 蓝图
blue = Blueprint('book', __name__)

# 要求:
# 	1.在书籍的book_index.html中有一个"查看所有书籍"的超链接按钮，点击进入书籍列表book_list.html页面.
# 	2.在书籍的book_list.html中显示所有书名，点击书名可以进入书籍详情book_detail.html
# 	3.在书籍book_detail.html中可以点击该书的作者和出版社，
#     	进入作者详情的author_detail.html和
#     	出版社详情的publisher_detail.html页面


@blue.route('/')
@blue.route('/bookindex/')
def book_index():
    return render_template('book_index.html')


@blue.route('/booklist/')
def book_list():
    books = Book.query.all()
    return render_template('book_list.html', books=books)


@blue.route('/bookdetail/<int:bid>/')
def book_detail(bid):
    book = Book.query.get(bid)
    return render_template('book_detail.html', book=book)


# 作者详情
@blue.route('/authordetail/<int:aid>/')
def author_detail(aid):
    author = Author.query.get(aid)
    return render_template('author_detail.html', author=author)


# 出版社详情
@blue.route('/publisherdetail/<int:pid>/')
def publisher_detail(pid):
    publisher = Publisher.query.get(pid)
    return render_template('publisher_detail.html', publisher=publisher)

00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/templates/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>作者详情</h2>
    <hr>

    <p>作者名称：{{ author.name }}</p>
    <p>作者年龄：{{ author.age }}</p>
    <p>作者性别：{{ author.sex }}</p>
    <p>作者Email：{{ author.email }}</p>
    <hr>

    <p>我的作品:
        {% for book in author.books %}
            <a href="/bookdetail/{{ book.id }}/">{{ book.title }}</a>
            {% if not loop.last %}|{% endif %}
        {% endfor %}
    </p>

</body>
</html>

00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/templates/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>书籍详情</h2>
    <hr>

    <p>书籍标题：{{ book.title }}</p>
    <p>书籍出版时间：{{ book.date }}</p>
    <p>作者：
        <a href="/authordetail/{{ book.auther.id }}/">{{ book.auther.name }}</a>
    </p>

    <p>出版社：
        {% for publisher in book.publishers %}
            <a href="/publisherdetail/{{ publisher.id }}/">{{ publisher.name }}</a>
            {% if not loop.last %}|{% endif %}
        {% endfor %}
    </p>

</body>
</html>

00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/templates/book_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>书籍首页</h2>
    <hr>

    <a href="/booklist/">查看所有书籍</a>

</body>
</html>

00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>书籍列表</h2>
    <hr>

    <ul>
        {% for book in books %}
            <li>
                <a href="/bookdetail/{{ book.id }}/">{{ book.title }}</a>
               {# <a href="{{ url_for('book.book_detail', bid=book.id) }}">{{ book.title }}</a>#}
            </li>
        {% endfor %}
    </ul>

</body>
</html>

00-完整代码/03-Flask模型/code/FlaskPro5_图书馆项目/App/templates/publisher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>出版社详情</h2>
    <hr>

    <p>出版社名称：{{ publisher.name }}</p>
    <p>出版社地址：{{ publisher.address }}</p>
    <p>出版社城市：{{ publisher.city }}</p>
    <p>出版社省份：{{ publisher.province }}</p>
    <p>出版社国家：{{ publisher.country }}</p>
    <p>出版社网址：{{ publisher.website }}</p>
    <hr>

    <p>出版社的出版书籍：
        {% for book in publisher.books %}
            <a href="/bookdetail/{{ book.id }}/">{{ book.title }}</a>
            {% if not loop.last %}|{% endif %}
        {% endfor %}
    </p>


</body>
</html>