02-Flask会话技术和Flask模板/FlaskPro1_会话技术cookie和session/App/__init__.py
# __init__.py :初始文件,创建Flask应用
import flask
from flask import Flask
from .views import *

# 创建Flask应用函数
def create_app():
        app = Flask(__name__)
        # 添加secret_key以启用session
        app.secret_key = 'your-secret-key-here'
        # 将蓝图注册到app中
        app.register_blueprint(blueprint=blue)
        app.register_blueprint(blueprint=product)
        return app

# app = flask.Flask(__name__)

02-Flask会话技术和Flask模板/FlaskPro1_会话技术cookie和session/App/views.py
# views.py 路由 + 视图函数
# 删除错误的导入，并添加正确的导入
import datetime

from flask import Blueprint, render_template, request, session, make_response, redirect

# 两种蓝图
blue = Blueprint('user', __name__)
product = Blueprint('product', __name__)


@product.route('/product')
# from .views import *时,蓝图和函数不能同名
def pro():
    return 'product'


# -------------------------------------------------------------------------------------------------------------------------------------------------------

@blue.route('/')
@blue.route('/index/')
def index_method():
    # 3.从cookie中获取用户名
    # username = request.cookies.get('user')

    # session版本
    username = session.get('user')

    # 4.将username传给模板
    return render_template('index.html', username=username)


@blue.route('/login/', methods=['GET', 'POST'])
def login_method():
    # 访问登录页面
    # 不是 else if ，而是 elif
    if request.method == 'GET':
        return render_template('login.html')
    # 点击登录按钮
    elif request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        print(username, password)

        if username == 'lisi' and password == '123':
            response = redirect('/index')

            # 1.将用户名和密码保存在cookies中(cookies中不能有中文)
            # response.set_cookie('user', username)

            # session版本
            session['user'] = username

            # 2.设置cookies过期时间
            # response.set_cookie('user', username, max_age=3600 * 24 * 7)
            # response.set_cookie('user', username, expires=datetime.datetime(2025, 12, 12))

            # session版本
            session.permanent = True

            # 登录成功后，跳转到首页
            return response
        else:
            return render_template('login.html', error='用户名或密码错误')
    return None


@blue.route('/logout/')
def logout_method():
    response = redirect('/index')

    # 5.删除cookies中的数据
    # response.delete_cookie('user')

    # session版本
    session.pop('user')
    return response

02-Flask会话技术和Flask模板/FlaskPro1_会话技术cookie和session/App/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>

<p>
    Index
</p>
{#{% if username %}#}
{% if session.user %}
    <p>
        {#        用户：{{ username }}#}
        用户：{{ session.user }}
        <br>
        <a href="/logout">注销</a>
    </p>
{% else %}
    {#get请求#}
    <a href="/login">Login</a>
{% endif %}

<hr>


</body>
</html>

02-Flask会话技术和Flask模板/FlaskPro1_会话技术cookie和session/App/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
{# 账号密码输入框 #}
<form action="" method="post">
{#正向解析:路由-->函数名#}
{#<form action="/login" method="post">#}
{#反向解析：蓝图函数名-->路由#}
{#<form action="{{ url_for('user.login_method') }}" method="post">#}
    账号:<input type="text" name="username">
    密码:<input type="password" name="password"><input type="submit" value="登录">
</form>
</body>
</html>